name: Publish docker image

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  IMAGE_NAME: ghcr.io/fablo-io/fablo-rest

jobs:
  publish-docker-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build fablo-rest
        run: npm install && npm run lint && npm run build && ls -lh ./dist

      - name: Read version
        run: |
          echo "DOCKER_IMAGE_VERSION=$(jq -r '.version' <"$GITHUB_WORKSPACE/package.json")" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=${{ env.DOCKER_IMAGE_VERSION }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Multi-arch platforms
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
