name: Publish docker image

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  IMAGE_NAME: softwaremill/fablo-rest

jobs:
  publish-docker-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build fablo-rest
        run: npm install && npm run lint && npm run build && ls -lh ./dist

      - name: Read version
        run: |
          echo "DOCKER_IMAGE_VERSION=$(jq -r '.version' <"$GITHUB_WORKSPACE/package.json")" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=${{ env.DOCKER_IMAGE_VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
