name: Test
on: [ push ]
jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build fablo-rest
        run: npm install && npm run lint && npm run build && ls -lh ./dist

      - name: Run unit tests
        run: npm run test

      - name: Build fablo-rest Docker image
        run: ./docker-build.sh

      - name: Start test network
        run: (ls -lh && cd ./test-network && ./fablo up fablo-config-tls.json)

      - name: Start fablo-rest as docker container and run e2e tests
        run: ./e2e/run-e2e-tests-on-dist.sh

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server.log
          path: server.log

      - name: Send Slack notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Fablo-REST CI
          SLACK_ICON: 'https://raw.githubusercontent.com/softwaremill/fablo/main/logo-sygnet-192.png'
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url,commit
