name: Test
on: [ push ]
jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build fabrica-rest
        run: npm install && npm run lint && npm run build && ls -lh ./dist

      - name: Start test network
        run: (ls -lh && cd ./test-network && ./fabrica up && ./force_chaincodes_ready.sh)

      - name: Start fabrica-rest in production mode
        run: (node dist/index.js > server.log &) && sleep 5

      - name: Run e2e tests
        run: npm run test-e2e

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server.log
          path: server.log

      - name: Send Slack notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Fabrica-REST CI
          SLACK_ICON_EMOJI: ':ouch_stone:'
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url,commit
